### ISSUE TITLE
botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by alexbransky** [aws-samples/aws-batch-rds-job-scheduling#1]
Newbie question: How do I tell the code or Docker what AWS creds to use?

Traceback (most recent call last):
  File "/code/main.py", line 61, in <module>
    job_exec()
  File "/code/main.py", line 29, in job_exec
    SecretId=secret_name
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 613, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by alexbransky** [comment]
I worked around it by hard-coding my access key/secret key/token, then the code worked without those once in ECR.

**Comment by pavrda** [comment]
Check `Job role ARN` settings in job definition. If it is empty, no credentials are injected into container.

**Comment by kushan-gunasekera** [comment]
Hope this answer will help you to avoid the above error with AWS Batch.

https://stackoverflow.com/a/72877747/6194097

This is the perfect solution.
